version: "3.9"

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq

    ports:
      - "5672:5672"
      - "15672:15672"

    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  product-db:
    image: postgres:16
    container_name: product-db

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: product_order_db

    ports:
      - "5433:5432"

    volumes:
      - product-db-data:/var/lib/postgresql/data

  customer-db:
    image: postgres:16
    container_name: customer-db

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: customer_db

    ports:
      - "5434:5432"

    volumes:
      - customer-db-data:/var/lib/postgresql/data

volumes:

  product-db-data:

  customer-db-data: